name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print event information
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: 'dockersample'  # ì²´í¬ì•„ì›ƒí•  ë””ë ‰í† ë¦¬ë¥¼ ì§€ì •í•©ë‹ˆë‹¤.

      - name: Install dependencies
        run: npm install
        working-directory: dockersample  # ì‘ì—…ì„ ì‹¤í–‰í•  ë””ë ‰í† ë¦¬ë¥¼ ì§€ì •í•©ë‹ˆë‹¤.

      - name: Run tests
        run: npm test
        working-directory: dockersample  # ì‘ì—…ì„ ì‹¤í–‰í•  ë””ë ‰í† ë¦¬ë¥¼ ì§€ì •í•©ë‹ˆë‹¤.
        continue-on-error: true

      - name: Build
        run: npm run build
        working-directory: dockersample  # ì‘ì—…ì„ ì‹¤í–‰í•  ë””ë ‰í† ë¦¬ë¥¼ ì§€ì •í•©ë‹ˆë‹¤.
        continue-on-error: true

      - name: Deploy
        run: ./deploy.sh
        if: success()
