name: GitHub Actions Demo
on:
  push:
    branches:
      - main # í‘¸ì‹œ ì´ë²¤íŠ¸ê°€ main ë¸Œëœì¹˜ì— ë°œìƒí•  ë•Œë§Œ ì‹¤í–‰ë©ë‹ˆë‹¤.
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print event information
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Run tests
        run: npm test # í”„ë¡œì íŠ¸ì˜ í…ŒìŠ¤íŠ¸ ìŠ¤í¬ë¦½íŠ¸ë¥¼ ì‹¤í–‰í•©ë‹ˆë‹¤.

      - name: Build
        run: npm run build # í”„ë¡œì íŠ¸ì˜ ë¹Œë“œ ìŠ¤í¬ë¦½íŠ¸ë¥¼ ì‹¤í–‰í•©ë‹ˆë‹¤.

      - name: Deploy
        run: ./deploy.sh # í”„ë¡œì íŠ¸ ë°°í¬ ìŠ¤í¬ë¦½íŠ¸ë¥¼ ì‹¤í–‰í•©ë‹ˆë‹¤.
        if: success() # í…ŒìŠ¤íŠ¸ ë° ë¹Œë“œê°€ ì„±ê³µí–ˆì„ ë•Œë§Œ ì‹¤í–‰ë©ë‹ˆë‹¤.

      - name: Send notification on failure
        run: ./send_notification.sh # ì‹¤íŒ¨ ì•Œë¦¼ ìŠ¤í¬ë¦½íŠ¸ë¥¼ ì‹¤í–‰í•©ë‹ˆë‹¤.
        if: failure() # í…ŒìŠ¤íŠ¸ ë˜ëŠ” ë¹Œë“œê°€ ì‹¤íŒ¨í–ˆì„ ë•Œë§Œ ì‹¤í–‰ë©ë‹ˆë‹¤.

